### ISSUE TITLE
 The output file does not write variation 6 and variation 7

### ISSUE THREAD

**Issue by vivaquo** [toolbox-labo/md-design-doc#23]
I wrote test variation 6 and 7 in the input file, but they were not reflected in the excel file.

- Input

```
# Sheet Name
## Test Variation 1
### Test Variation 1-2
#### Test Variation 1-2-3
##### Test Variation 1-2-3-4
###### Test Variation 1-2-3-4-5
####### Test Variation 1-2-3-4-5-6
######## Test Variation 1-2-3-4-5-6-7
* Test Description
  more lines...
  more lines...
### Test Variation 1-2
・・・
```

- Output

![image](https://user-images.githubusercontent.com/77032145/107149124-3b8e6580-699a-11eb-8a2a-58538d176b52.png)

**Comment by ymtdzzz** [comment]
@vivaquo
This issue was solved in #32 , so I close this.

![image](https://user-images.githubusercontent.com/44557218/107359851-87ffaf80-6b18-11eb-84a0-290b1e8703e9.png)

Please reopen if there's something wrong.
