### ISSUE TITLE
I want to output a debug log when I exexute it

### ISSUE THREAD

**Issue by vivaquo** [toolbox-labo/md-design-doc#28]
Log output isn't available now, so I want to enable it!

**Comment by ymtdzzz** [comment]
Hey @vivaquo , I've added the feature of logging.
If you want to output debug logs, use logging macros in `log` crate such as `info!` and pass the argument `-v (print info logs)` or `-d (also print debug logs)`.
See for the detail: https://docs.rs/log/0.4.14/log/#macros
